[template]  
src = "haproxy.cfg.tmpl"  
dest = "/etc/haproxy/haproxy.cfg"  
keys = [  
  "/services/",  
]  
check_cmd = "/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -c "
reload_cmd = "systemctl reload haproxy"  
